image: node:10.0.0

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

  - npm install gatsby-cli@1.1.51 --global
# commands after npm install did not run so making npm install last.
  - npm install

buildGatsby_develop:
  stage: build
  environment:
    name: develop
  script:
    - git clone https://github.com/HumanCellAtlas/metadata-schema.git _metadata-schema
    - npm install gatsby-cli@1.1.51 --global
    - export GATSBY_EXPLORE_URL=https://dev.explore.data.humancellatlas.org/
    - gatsby build
     - npm install gatsby-cli@1.1.51 --global
    # commands after npm install did not run so making npm install last.
      - npm install
  artifacts:
    paths:
    - public
  only:
    - develop

buildGatsby_integration:
  stage: build
  environment:
    name: integration
  script:
    - git clone https://github.com/HumanCellAtlas/metadata-schema.git _metadata-schema
    - npm install gatsby-cli@1.1.51 --global
    - export GATSBY_EXPLORE_URL=https://integration.explore.data.humancellatlas.org/
    - gatsby build
  artifacts:
    paths:
    - public
  only:
    - integration

buildGatsby_staging:
  stage: build
  environment:
    name: staging
  script:
    - git clone https://github.com/HumanCellAtlas/metadata-schema.git _metadata-schema
    - npm install gatsby-cli@1.1.51 --global
    - export GATSBY_EXPLORE_URL=https://staging.explore.data.humancellatlas.org/
    - gatsby build
  artifacts:
    paths:
    - public
  only:
    - staging

develop_deploy:
  stage: deploy
  image: python:3.5
  environment:
    name: develop
  script:
    - export BUCKET=s3://dev.data.humancellatlas.org/
    - pip install awscli --upgrade --user
    - aws s3 sync --acl public-read public/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
  only:
    - develop

integration_deploy:
  stage: deploy
  image: python:3.5
  environment:
    name: integration
  script:
    - export BUCKET=s3://integration.data.humancellatlas.org/
    - pip install awscli --upgrade --user
    - aws s3 sync --acl public-read public/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
  only:
    - integration

staging_deploy:
  stage: deploy
  image: python:3.5
  environment:
    name: staging
  script:
    - export BUCKET=s3://staging.data.humancellatlas.org/
    - pip install awscli --upgrade --user
    - aws s3 sync --acl public-read public/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
  only:
    - staging
