
stages:
  - build
  - deploy

cache:
  paths:
  - node_modules/

# Build Jobs
# Build Job Template
.build_template: &build_template
  image: node:10.0.0
  stage: build
  before_script:
    - git clone https://github.com/HumanCellAtlas/metadata-schema.git _metadata-schema
    - npm install gatsby-cli@1.1.51 --global
    - npm install
  artifacts:
      paths:
        - public

# Develop Build
build_develop:
  <<: *build_template
  environment:
    name: develop
  script:
    - export GATSBY_EXPLORE_URL=https://dev.data.humancellatlas.org/explore/
    - gatsby build
  only:
    - develop

# Integration Build
build_integration:
  <<: *build_template
  environment:
    name: integration
  script:
    - export GATSBY_EXPLORE_URL=https://integration.data.humancellatlas.org/explore/
    - gatsby build
  only:
    - integration

# Staging Build
build_staging:
  <<: *build_template
  environment:
    name: staging
  script:
    - export GATSBY_EXPLORE_URL=https://staging.data.humancellatlas.org/explore/
    - gatsby build
  only:
    - staging

########################################
# Deploy Jobs
########################################


# Deploy Job Template
.deploy_template: &deploy_template
  stage: deploy
  image: python:3.5
  before_script:
    - pip install awscli

# Dev Deploy
deploy_develop:
  <<: *deploy_template
  environment:
    name: develop
  script:
    - export BUCKET=s3://dev.data.humancellatlas.org/
    - aws s3 sync --acl public-read public/ $BUCKET --delete
    - aws s3 cp ${BUCKET}index.html ${BUCKET}index.html --metadata-directive REPLACE --cache-control max-age=0
    - aws cloudfront create-invalidation --distribution-id EDQUW4UP25O4L --paths "/*"
  only:
    - develop
# Integration Deploy
deploy_integration:
  <<: *deploy_template
  environment:
    name: integration
  script:
    - export BUCKET=s3://integration.data.humancellatlas.org/
    - aws s3 sync --acl public-read public/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id E2MB44J9QEJOYP --paths "/*"
  only:
    - integration

# Staging Deploy
deploy_staging:
  <<: *deploy_template
  environment:
    name: staging
  script:
    - export BUCKET=s3://staging.data.humancellatlas.org/
    - aws s3 sync --acl public-read public/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id E38D6Y96QKYO6 --paths "/*"
  only:
    - staging
