image: node:10.0.0

stages:
  - build

cache:
  paths:
    - node_modules/

before_script:
  - git clone https://github.com/HumanCellAtlas/metadata-schema.git _metadata-schema
  - npm install gatsby-cli@1.1.51 --global
  - npm install


buildGatsby:
  stage: build
  environment: develop
  script:
    - gatsby build
  artifacts:
    paths:
    - public
  only:
    - develop