image: node:10.0.0

stages:
  - build
  - deploy

cache:
  paths:
  - node_modules/

# Build Jobs
# Build Job Template
.build_template:
  stage: build
  before_script:
    - git clone https://github.com/HumanCellAtlas/metadata-schema.git _metadata-schema
    - npm install gatsby-cli@1.1.51 --global
    - npm install
  artifacts:
      paths:
        - public

# Develop Build
build_develop:
  extends: .build_template
  environment:
    name: develop
  script:
    - export GATSBY_EXPLORE_URL=https://dev.explore.data.humancellatlas.org/
    - gatsby build
  only:
    - develop

# Integration Build
build_integration:
  extends: .build_template
  environment:
    name: integration
  script:
    - export GATSBY_EXPLORE_URL=https://integration.explore.data.humancellatlas.org/
    - gatsby build
  only:
    - integration

# Staging Build
build_staging:
  extends: .build_template
  environment:
    name: staging
  script:
    - export GATSBY_EXPLORE_URL=https://staging.explore.data.humancellatlas.org/
    - gatsby build
  only:
    - staging

# Deploy Jobs
# Deploy Job Template
.deploy_template:
  stage: deploy
  image: python:3.5
  before_script:
    - pip install awscli --upgrade --user

develop_deploy:
  extends: .deploy_template
  environment:
    name: develop
  script:
    - export BUCKET=s3://dev.data.humancellatlas.org/
    - aws s3 sync --acl public-read public/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
  only:
    - develop

integration_deploy:
  extends: .deploy_template
  environment:
    name: integration
  script:
    - export BUCKET=s3://integration.data.humancellatlas.org/
    - aws s3 sync --acl public-read public/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
  only:
    - integration

staging_deploy:
  extends: .deploy_template
  environment:
    name: staging
  script:
    - export BUCKET=s3://staging.data.humancellatlas.org/
    - aws s3 sync --acl public-read public/ $BUCKET --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
  only:
    - staging
