image: node:10.0.0

stages:
  - build

cache:
  paths:
    - node_modules/

before_script:
  - git clone https://github.com/HumanCellAtlas/metadata-schema.git _metadata-schema
  - npm install gatsby-cli@1.1.51 --global
# commands after npm install did not run so making npm install last.
  - npm install


buildGatsby_develop:
  stage: build
  environment:
    name: develop
  script:
    - export GATSBY_EXPLORE_URL=https://dev.explore.data.humancellatlas.org/
    - gatsby build
  artifacts:
    paths:
    - public
  only:
    - develop


buildGatsby_integration:
  stage: build
  environment:
    name: integration
  script:
    - export GATSBY_EXPLORE_URL=https://integration.explore.data.humancellatlas.org/
    - gatsby build
  artifacts:
    paths:
    - public
  only:
    - integration

buildGatsby_staging:
  stage: build
  environment:
    name: integration
  script:
    - export GATSBY_EXPLORE_URL=https://staging.explore.data.humancellatlas.org/
    - gatsby build
  artifacts:
    paths:
    - public
  only:
    - staging