language: python
cache:
  pip: true
python:
- 3.6
dist: trusty
addons:
  apt:
    packages:
    - npm
before_install:
- pip install awscli --upgrade
- npm install gatsby-cli --global
install: npm install
script: make build
deploy:
  - provider: script
    script: make deploy-staging-travis
    skip_cleanup: true
    on:
      branch: staging
  - provider: script
    script: make deploy-dev-travis
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: make deploy-integration-travis
    skip_cleanup: true
    on:
      branch: integration
env:
  global:
    - secure: sU3B8oaXlnbVKyET2Sy2qJIriahBfGq7uJlm0VKb6zAkG4xUyeFEUfXmG9w3oddHbXBPu8gX9OfTNlRqzB+XYhW7gsW0mu+8JJY30ioin8ESze0dvSsuaTEari8dIjc/KFi2LVJmH5zfmIl4yV7Cn0NGz93loCwr0pWxH0hAX7wbmVQalullKloszv4MGyYKAOGlVOHOZyGrAP4/j02sIyh2CYt5RVbRSxD+VP55cJJWXSYjCZ3ljI5Dj6cYfFHX44QAQ2dxAu0WhbwYXdMUGJEc4/1t9Foiod10g5U+aAL+GFBmeeViu9GmDWmdzuv/E+Hi49fD25QgWFFb8DeF60vGdRzzCEHb7Q24OeC98/KtJPpjePAPRam3eX01Qg6trIloA3dHjf4cNvMTFCo3qH+YxovP0PCxTy5146J1FNfkCfhJPOGdWYcI/HndKKjfSAry99TDLJ4R0uKXrHY+qKcrbUrJrv2pbcnYpyV064wejmEDZvNLi5tAnzcpaLjnXRF1HDNuvt1Sl3W9O6NAB9EZkDFNipbqc9KrIlDV+ewBovrzUxXvdPLXy1/vWWwKjNySDwy4XqEHb7cRg+vVUG+9sX5UWY9nqLoACeR8RTd/OYLpu9fZaJ29VJ7tg/UYOyjFnAdV5Z4Mmq5u6pUGtZtOpFnogVG8qGTB4FsDpDA=
    - secure: jvQ3Dnj0Z0IbjREDHFa//M3ZyOSdaRroCJDOQpqcuon1q2/C5dSkWwiBdmTwukJaS4+PesoLgJfqB8ACOVvXpWqyMZaMGoW09kAHRo/cd1l3pnerQ0674n3Hkc6MbiASrQ5/56Q/gBGQW0LaKMcjPVmiJuNGn4oLWIlNwC6//PNnMVsIzDvZODRj3pH/ucZJMcFG/w2wfUtkdTHt6ySvVPVZ01IzyuT+HR4ChKhlOaMgPf2aHAbClhjzDIEC8WLygRmZJKF8Zl1zbTIgW0ThpjT/EdXEa4uaUNbnEuq4FsWVe7rUPEn8Fpo1EMLHB10K0ajXniqkCTeG9UA4Qmh1fFA2bR8yNpeLazrk1MlPIr8wGR/SupT9OMwxiO0O8NRBgxwTfzWRWhOJ247J8hCwr05YbhluyJV3BfTadxmj2rFQIp6pxtPr1zf5MBT6hZcduA9Rt2qijGp++pezyGzQUjRlnwOqRmTMQBH5dsaWxu/svZSzaSYKQGuB1JYuz02qNW8NDe5TSwE7TzJ1hyBJ6qUwofJfIoj0qQNAWrJ91okY4HcyPXvJ0yF4ZYvDF4TOhbM3S0a9UQb2wqzzz67fZ8SFQuYnIqUF7Z+i8RCT2gFAE60nsrBQE572zmLhOqY4D8guI4AI79CDHQ133kWoRNhRdYbVNXXDy+kYSonHKvg=
    - secure: WkLzFOPPEmPy0vuVzvxdSnZFolFopEwwnXZB1d/OU4xE+T5H945JXEIdJ8VOu5Di0FKcIJPaicgyIgEGh5nRkbTWrFVdgHSgetLON0weC2GVvS3SaoB1Xr6KG8eLfi13sjAPCZUQu/ROa4UfFJM8lXFEzt/pxxDhUd/cqLGVp7pnHvbFZYi6hcc41xYfqn8L2/NZikWbem/VHLOH5mI9ERJUHh6DiKvhSbepAQpIZW6L7hg6yKIEIrH9KwYUJ/MM4N3DCkND2s0D22JhX3GKUK1zUIYlGGamcCoIQomdryS/4kquJS4lA4TUDLsNszgX7Y9TGiaIsJ46TH+bmolS8Ww9c+kwalSXJl8MRpGl5dH23b0WwaI4X2gzkFC6Bheci/tqtN3HY34DMYV7rxGKF1ktdgqkF/9Tx4HBVbKAj3dT7y+H2FPz8zI/sTuSYmNMa4ezNuRZPcp4b55K9GEgBFb/flnuLaiLT+AsRA9tz3AXWsDeg4hwGNf4olg0pNJOIEXUyP/cDh4v0vDCw7jFVTtVvH0753rGYM/+6SSBFtMIbIb3Dfktf/hdpkI5VS/LV8TC06zUI1x6dhTIumWkN9S5Xxzv0FxTwk5EGalNgI+SPrkXnFInI4KhMDE721nZF/s1/+WsTfIdXXMc8IZ8Eyir3y1bMae51c+AAtlwBKQ=
    - secure: zot85ZtY3Utr1GfSBUEFNbhQRxAXMWMzeMLmJaGa3ppATQpS6+XFDi+vgHda8TT6Qk4crj+uunJ6Pp2hTMTSB+uywVufp2FRk2yGEOuD74GbRVwTGNO68C5HaM37iHhqMFWihkumI5qRcsBzqjKd6nmYVQnWuARUgnDKevsiHElYowzsuvWRhfMrc0yMumV7F/aevkkxF+/YcxAkpVA0zRPwlS/vkLjbKBYP7Dd503eNefvP/TYdJGhMBJIUtj3N2n7Dg75VAm07xCM5WVL5rqIlehV9dtwDBkgFE7DhAwXMdEuMzzbT36VyoWM78lzV+8xl3/7UCG7gPl06kydf9dFSdqjpaEt3sQVLa33ESJnvhudMMGtdhbz2gITInHZozMH35ek3n0n3UOHiksDDTZdyLvEA2hplmO6DRLknq6xqlFkbp1U2bXNWBQL8Gl3nqn+p8eaP0tDo+St04M68GvJacrbEdpPHmBx8+TekpFgm+mXH/C7srgB0zY9ivNKWk/EQ2ZS0m+sMpcvTsdpeXTUf/cRGcZb0/9/ghx6/i4W2UcaSiP5QfpQWjfY50GegEr9oIZtfPohaEubs/2GTBxhS8rS1GjfKBngp9vZGov4GorRevfAFxq/GBoZhmPnIe8Rh87gm1jiYZiHSjnhmHn3OHnNN4mhBW4pBgbz7vAw=
    - secure: ecvhd1vlTAbyDt/FQsXsnPR2OYYsh7LcFJYlmYrizuRqmRhwmEask0VZc19fQ279XgJGkrOkZMyHfXbhm2nz5BS8/n8DjGg2BizKWn2XySzpAu6z5gTbSVBqMhSZvfy9QYkde3O1tZZEuwIk9GM9+84Wie85yETmcBcBrLL2NExH2om2J7UwPCNxQOy95gquuYZk5pfWvUqmF5On87VbwXJuNZ/5aB2m4u8yjerCWtBehPdfWg/p195xjh/DRV2c/mOCSiUp9UldqYji3/rwge5eOEHxOzCGROxk5VXWZamtn07hLlMLwQRjurIcIBzjM10cbJ0tbP3pETr2STJz5UWXZqeUtthqV7Tx8iI12UQ8Qs6tmHmcCPThDITv9/q+KjcRQTdqS23426bJ7XXvSL5Bvn859JQvuLY68k0CpCWlW36EclPgXkw2GDD62SsNgIgj9jYVRQyrUxZpFHtPmbcr0uLbVO6bgmwPzbqpYnwRUU7CQX8mR0+Un65rLNRF3DGM5vTvd79rftz0uJnG1vwUPursd6g7Oci5vupxdkRmoqy9TuwuJK/+hSBgvAgsJFcvCL9ax4ZoG/x5tEKk4i9gbDOALnM9XOlO1kpENagIAOGKkOvt4RnGgNwvDokwAs4tuoOUdFsc05eLkcuMiTR8np/u4rU+Vc/v3CPO1aM=
