language: python
cache:
  pip: true
python:
- 3.6
dist: trusty
addons:
  apt:
    packages:
    - npm
before_install:
- pip install awscli --upgrade
install: npm install
script: make build
deploy:
  provider: script
  script: make deploy-staging-travis
  skip_cleanup: true
  on:
    branch: staging
env:
  global:
    - secure: sU3B8oaXlnbVKyET2Sy2qJIriahBfGq7uJlm0VKb6zAkG4xUyeFEUfXmG9w3oddHbXBPu8gX9OfTNlRqzB+XYhW7gsW0mu+8JJY30ioin8ESze0dvSsuaTEari8dIjc/KFi2LVJmH5zfmIl4yV7Cn0NGz93loCwr0pWxH0hAX7wbmVQalullKloszv4MGyYKAOGlVOHOZyGrAP4/j02sIyh2CYt5RVbRSxD+VP55cJJWXSYjCZ3ljI5Dj6cYfFHX44QAQ2dxAu0WhbwYXdMUGJEc4/1t9Foiod10g5U+aAL+GFBmeeViu9GmDWmdzuv/E+Hi49fD25QgWFFb8DeF60vGdRzzCEHb7Q24OeC98/KtJPpjePAPRam3eX01Qg6trIloA3dHjf4cNvMTFCo3qH+YxovP0PCxTy5146J1FNfkCfhJPOGdWYcI/HndKKjfSAry99TDLJ4R0uKXrHY+qKcrbUrJrv2pbcnYpyV064wejmEDZvNLi5tAnzcpaLjnXRF1HDNuvt1Sl3W9O6NAB9EZkDFNipbqc9KrIlDV+ewBovrzUxXvdPLXy1/vWWwKjNySDwy4XqEHb7cRg+vVUG+9sX5UWY9nqLoACeR8RTd/OYLpu9fZaJ29VJ7tg/UYOyjFnAdV5Z4Mmq5u6pUGtZtOpFnogVG8qGTB4FsDpDA=
    - secure: jvQ3Dnj0Z0IbjREDHFa//M3ZyOSdaRroCJDOQpqcuon1q2/C5dSkWwiBdmTwukJaS4+PesoLgJfqB8ACOVvXpWqyMZaMGoW09kAHRo/cd1l3pnerQ0674n3Hkc6MbiASrQ5/56Q/gBGQW0LaKMcjPVmiJuNGn4oLWIlNwC6//PNnMVsIzDvZODRj3pH/ucZJMcFG/w2wfUtkdTHt6ySvVPVZ01IzyuT+HR4ChKhlOaMgPf2aHAbClhjzDIEC8WLygRmZJKF8Zl1zbTIgW0ThpjT/EdXEa4uaUNbnEuq4FsWVe7rUPEn8Fpo1EMLHB10K0ajXniqkCTeG9UA4Qmh1fFA2bR8yNpeLazrk1MlPIr8wGR/SupT9OMwxiO0O8NRBgxwTfzWRWhOJ247J8hCwr05YbhluyJV3BfTadxmj2rFQIp6pxtPr1zf5MBT6hZcduA9Rt2qijGp++pezyGzQUjRlnwOqRmTMQBH5dsaWxu/svZSzaSYKQGuB1JYuz02qNW8NDe5TSwE7TzJ1hyBJ6qUwofJfIoj0qQNAWrJ91okY4HcyPXvJ0yF4ZYvDF4TOhbM3S0a9UQb2wqzzz67fZ8SFQuYnIqUF7Z+i8RCT2gFAE60nsrBQE572zmLhOqY4D8guI4AI79CDHQ133kWoRNhRdYbVNXXDy+kYSonHKvg=
    - secure: WfalYP3HjelWZn+tb6XajAtqBJaCpFN4vFOjYp7cEWN5bgb0e7Oc62sSmbx9eIJpFHpJKelQ6HkhuIezerHwWFToZPdYMVbz78ruFA08+1dc91UqwjuJs4G6kzZKL7SltRnKErnn+5ZfXpBGCj1P1XFEF70CSbd7UGPao5/EDVhBam1NWuyKBFceqUExMRMiWVNKNVnw0h5UF+xp79XQy2OpUSqr6Ox6Q+hnqKN3MnpsAZtZi0DSdOLCocb8sv81mBSokGtQoVd+NgkE9GgNboDFwdNnK11GlQAGjvwpjgXrMa14Jid9GvQPDZRgx7FC7PPrVepqC0hmSBl+1H6k0v6/fYbNOhpucOnbLFNZYttrSNukmuAHnu/WolY+8cB//0lIfrRlPqF0R44YHDZII+fa65mxTloXVDIhnNtn/HMrGc8NM+cZf8AjwbScm0b9IuKJFq4Qr0Z8n64hz8ZGCFqBl2KrSF4vo804gm5oml14lN0VXxRaOwS/8t2YSfkuadlP6oBDw3/z0NhM4ePjlrRAv0G4o43y2VWYXeE0fkLy+oG9xMfWxh8IDfBHxy3PEHcBpbRlY1scoVFwgz0ICjEwZvYHU4Ph1/2udqAmCLZvy9UQ8CauOren/O8FF7ixAOfX9Us/EHuUlTvYmK6VC8hyy4Q6pCjcUaweLVuvM/s=